### ISSUE TITLE
Review of project #1

### ISSUE THREAD

**Issue by najla23** [teokem/project-work-2020-amaerisk#1]
Dear Amanda,

I like the aim of your Jupyter as a lab guide, informative Jupyter ;)
Just, I think it's better to add a composite plot and figures.
DOI is missing :) 
BTW, instead of uploading your file, you can use terminal (git init,...,git push origin master), it's really fast ;)

All the best, Najla

**Comment by amaerisk** [comment]
Dear Najla,

Thank you for your nice comments, I will add the DOI as you mentioned. Regarding the composite plots, I thought that the double axis plot would count as a composite plot, but maybe I understood it incorrectly. :)

Best,

Amanda
